'use server';
/**
 * @fileOverview A Genkit flow for generating reflective questions based on media capture notes.
 *
 * - generateReflectiveQuestions - A function that handles the generation of reflective questions.
 * - GenerateReflectiveQuestionsInput - The input type for the generateReflectiveQuestions function.
 * - GenerateReflectiveQuestionsOutput - The return type for the generateReflectiveQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateReflectiveQuestionsInputSchema = z.object({
  mediaTitle: z.string().describe('The title of the media item.'),
  beforePriorBeliefs: z.string().optional().describe('User\u0027s prior beliefs about the topic before consuming the media.'),
  beforeExpectation: z.string().optional().describe('User\u0027s expectations or hopes before consuming the media.'),
  beforeOpenQuestion: z.string().optional().describe('An open question the user had before consuming the media.'),
  afterCoreArgument: z.string().optional().describe('The core argument or main claim from the media after consumption.'),
  afterLastingIdea: z.string().optional().describe('A lasting idea or takeaway from the media.'),
  afterBeliefChange: z.string().optional().describe('How the media changed something the user believed.'),
});
export type GenerateReflectiveQuestionsInput = z.infer<typeof GenerateReflectiveQuestionsInputSchema>;

const GenerateReflectiveQuestionsOutputSchema = z.array(z.string()).describe('A list of reflective questions generated by the AI.');
export type GenerateReflectiveQuestionsOutput = z.infer<typeof GenerateReflectiveQuestionsOutputSchema>;

export async function generateReflectiveQuestions(input: GenerateReflectiveQuestionsInput): Promise<GenerateReflectiveQuestionsOutput> {
  return generateReflectiveQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateReflectiveQuestionsPrompt',
  input: {schema: GenerateReflectiveQuestionsInputSchema},
  output: {schema: GenerateReflectiveQuestionsOutputSchema},
  prompt: `You are an AI assistant specialized in critical thinking and reflection. Your task is to generate a set of thought-provoking reflective questions based on the provided notes for a media item.

The questions should aim to:
- Challenge the user's assumptions.
- Encourage deeper inquiry and connection of ideas.
- Explore the relationship between 'before' and 'after' perspectives.
- Be open-ended and promote personal reflection, not simple yes/no answers.

Media Title: {{{mediaTitle}}}

Before Consumption:
{{#if beforePriorBeliefs}}  Prior Beliefs: {{{beforePriorBeliefs}}}
{{/if}}{{#if beforeExpectation}}  Expectations: {{{beforeExpectation}}}
{{/if}}{{#if beforeOpenQuestion}}  Open Question: {{{beforeOpenQuestion}}}
{{/if}}
After Consumption:
{{#if afterCoreArgument}}  Core Argument: {{{afterCoreArgument}}}
{{/if}}{{#if afterLastingIdea}}  Lasting Idea: {{{afterLastingIdea}}}
{{/if}}{{#if afterBeliefChange}}  Belief Change: {{{afterBeliefChange}}}
{{/if}}

Generate 3-5 reflective questions based on these notes.`,
});

const generateReflectiveQuestionsFlow = ai.defineFlow(
  {
    name: 'generateReflectiveQuestionsFlow',
    inputSchema: GenerateReflectiveQuestionsInputSchema,
    outputSchema: GenerateReflectiveQuestionsOutputSchema,
  },
  async (input) => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('Failed to generate reflective questions.');
    }
    return output;
  }
);
